name: PR and Merge

on:
  workflow_dispatch:

jobs:
  pr-and-auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Configure Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          
      - name: Create and Push Branch
        run: |
          git checkout -b gh-actions
          git push origin gh-actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-actions
          title: 'Automated PR'
          body: 'This PR adds new updates'
          labels: 'automerge'

      - name: Enable Auto-Merge
        uses: pascalgn/automerge-action@v0.16.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
